# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - web-api-capta

on:
    push:
        branches:
            - main
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
            contents: read #This is required for actions/checkout

        steps:
            - uses: actions/checkout@v4

            - name: Set up Node.js version
              uses: actions/setup-node@v3
              with:
                  node-version: "20.16.0"

            - name: npm install, test
              run: |
                  npm install
                  npm run test --if-present
                  npm run build --if-present

            - name: Upload artifact for deployment job
              uses: actions/upload-artifact@v4
              with:
                  name: node-app
                  path: .

    deploy:
        runs-on: ubuntu-latest
        needs: build
        permissions:
            id-token: write #This is required for requesting the JWT
            contents: read #This is required for actions/checkout

        steps:
            - name: Download artifact from build job
              uses: actions/download-artifact@v4
              with:
                  name: node-app

            - name: Login to Azure
              uses: azure/login@v2
              with:
                  client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_BEB6B07821DA47538B829D21E8DF83A9 }}
                  tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_15C086AE5AB248F49FA269BEA7DF06B3 }}
                  subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_A3E9FD35377A40B298791A0CE9EE5E47 }}

            - name: "Deploy to Azure Web App"
              id: deploy-to-webapp
              uses: azure/webapps-deploy@v3
              with:
                  app-name: "web-api-capta"
                  slot-name: "Production"
                  package: .
