name: Build and deploy Node.js app to Azure Web App - web-api-capta

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read # Required for actions/checkout

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Validate API version
        run: "echo Deploying API version: $API_VERSION"

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies, run tests, build
        env:
          PORT: ${{ secrets.PORT }}
          API_CAPTA_HOLYDATES: ${{ secrets.API_CAPTA_HOLYDATES }}
          API_VERSION: ${{ secrets.API_VERSION }}
        run: |
          npm ci
          npm run dev &&
          npm run test --coverage --if-present

      - name: Build application
        run: |
          npm run build

      - name: Prepare deployment package
        run: |
          mkdir deploy
          cp package*.json deploy/
          cp -r dist deploy/

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: deploy/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write # Required for Azure login via OIDC
      contents: read

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_BEB6B07821DA47538B829D21E8DF83A9 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_15C086AE5AB248F49FA269BEA7DF06B3 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_A3E9FD35377A40B298791A0CE9EE5E47 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: "web-api-capta"
          slot-name: "Production"
          package: deploy/
